feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: $DATASET/train_$STREAM.npy
  label_path: $DATASET/train_label.pkl
  debug: False

test_feeder_args:
  data_path: $DATASET/val_$STREAM.npy
  label_path: $DATASET/val_label.pkl


model: model.msg3d.Model
model_args:
  # num_class: 502
  num_class: REQUIRED
  num_point: 61
  num_person: 1
  num_gcn_scales: 8
  num_g3d_scales: 8
  in_channels: REQUIRED
  graph: graph.mediapipe61.AdjMatrixGraph

tta : [
  [False,1],
  [True,1],
  ]

