#########################  MODELS SETTINGS  #########################

MODEL_DELEGATE: 1  # 0: CPU, 1: GPU
RUNNING_MODE: 0  # 0: VIDEO, 1: IMAGE

# MEDIAPIPE HOLISTIC LEGACY
HOLISTIC_LEGACY_STATIC_IMAGE_MODE: False
HOLISITC_LEGACY_MODEL_COMPLEXITY: 2
HOLISTIC_LEGACY_SMOOTH_LANDMARKS: True
HOLISTIC_LEGACY_MIN_DETECTION_CONFIDENCE: 0.5
HOLISTIC_LEGACY_MIN_TRACKING_CONFIDENCE: 0.5

# MEDIAPIPE POSE
POSE_NUM_POSES: 1
POSE_MIN_POSE_DETECTION_CONFIDENCE: 0.5
POSE_MIN_POSE_PRESENCE_CONFIDENCE: 0.5
POSE_MIN_TRACKING_CONFIDENCE: 0.5
POSE_OUTPUT_SEGMENTATION_MASK: False

# MEDIAPIPE HANDS
HANDS_NUM_HANDS: 2
HANDS_MIN_HAND_DETECTION_CONFIDENCE: 0.5
HANDS_MIN_HAND_PRESENCE_CONFIDENCE: 0.5


#########################  KEYPOINTS SETTINGS  #########################

NUM_KPS: 61
NUM_CHANNELS: 4
MAX_FRAMES: 100
THRESHOLD_SCORE: 0.5
NUM_PERSON: 1

IDX_KPS_POSE: [0, 2, 5, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]   # 19 ELEMENTS  # POSICIONES DE MEDIAPIPE POSE QUE UTILIZAMOS - LOS 19 PRIMEROS ELEMENTOS DEL ARRAY QUE UTILIZAMOS.
KEYPOINTS_INCLUDE: [
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, # pose
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,  # left hand
        40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60  # right hand
        ]
CONNECTIONS: [
        [0,0],[0,1],[0,2],[1,3],[2, 4],[0,5],[0,6],[5,7],[6,8],[7,9],[8,10], [9, 11], [10, 12], [9,13], [10, 14], [9,15], [10, 16] ,[5,17], [6,18],
        [9, 19], [19, 20], [20, 21], [21, 22], [22, 23], [19, 24], [24, 25], [25, 26], [26, 27], [19, 28], [28, 29], [29, 30], [30, 31], [19, 32], [32, 33], [33, 34], [34, 35], [19, 36], [36, 37], [37, 38], [38, 39],
        [10, 40], [40, 41], [41, 42], [42, 43], [43, 44], [40, 45], [45, 46], [46, 47], [47, 48], [40, 49], [49, 50], [50, 51], [51, 52], [40, 53], [53, 54], [54, 55], [55, 56], [40, 57], [57, 58], [58, 59], [59, 60]
        ]
ANGLES: [
        [0,1,2],[1,0,3],[2,0,4],[0,5,6],[0,3,5],[0,4,6],[5,6,7],[6,5,8],[7,5,9],[8,6,10],[9,7,11],[10,8,12],[9,7,11],[10,8,14],[9,7,13],[6,8,18],[5,17,7],[5,6,17],[5,6,18],
        [5,9,19],[20,19,21],[21,20,22],[22,21,23],[19,9,23],[24,19,25],[25,24,26],[26,25,27],[19,9,27],[28,19,29],[29,28,30],[30,29,31],[19,9,31],[32,19,33],[33,32,34],[34,33,35],[19,9,35],[36,19,37],[37,36,38],[38,37,39],[19,9,39],
        [6,10,40],[41,40,42],[42,41,43],[43,42,44],[40,10,44],[45,40,46],[46,45,47],[47,46,48],[40,10,48],[49,40,50],[50,49,51],[51,50,52],[40,10,52],[53,40,54],[54,53,55],[55,54,56],[40,10,56],[57,40,58],[58,57,59],[59,58,60],[40,10,60]
     ]

# IMPORTANT POSITIONS
POSE_POSITION_SHOULDER_LEFT: 5
POSE_POSITION_SHOULDER_RIGHT: 6

POSE_POSITION_WRIST_LEFT: 9
POSE_POSITION_WRIST_RIGHT: 10

HANDS_POSITION_WRIST_LEFT: 19
HANDS_POSITION_WRIST_LEFT_LAST_IDX: 39
HANDS_POSITION_WRIST_RIGHT: 40
HANDS_POSITION_WRIST_RIGHT_LAST_IDX: 60
